export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOG_OUT = "LOG_OUT";

export const CONTACT_LIST_REQUEST = "CONTACT_LIST_REQUEST";
export const CONTACT_LIST_SUCCESS = "CONTACT_LIST_SUCCESS";
export const CONTACT_LIST_NULL = "CONTACT_LIST_NULL";
export const CONTACT_LIST_FAIL = "CONTACT_LIST_FAIL";

export const DELETE_CONTACT_START = "DELETE_CONTACT_START";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";

export const POST_CONTACT_START = "POST_CONTACT_START";
export const POST_CONTACT_FAIL = "POST_CONTACT_FAIL";
export const POST_CONTACT_SUCCESS = "POST_CONTACT_SUCCESS";
